### ISSUE TITLE
Which 3D file types does seen support?

### ISSUE THREAD

**Issue by headwinds** [themadcreator/seen#13]
In your demo, you load 3D data from an external file and render a rabbit. Very cool!

Does seen support other types of 3D files like collada or only that type in the demo?

**Comment by themadcreator** [comment]
Currently it only supports wavefront .obj files since they have a very
simple grammar and there exist many tools to convert triangular meshes to
this format. We also support .bvh motion capture files, as seen in the
mocap demo.

**Comment by headwinds** [comment]
thanks! I'm using Blender and see that it does export to the obj file format so I'm good to go - I'm super impressed with seenjs but have just scratched the surface - I started attempting to port the canvas wave example to a [SVG version](http://www.headwinds.net/lab/porthole/wave.html ) - next I'd like to try low poly models...

**Comment by themadcreator** [comment]
Cool! You should just be able to pass in an svg element to the seen.Context
call and itll use the svg render methods.

See the comparison example:
http://seenjs.io/demo-svg-canvas.html

**Comment by headwinds** [comment]
I'll look at the example... not sure which line you mean?! can you write it one line for me?

I went a bit further into my experiment last night [adding a low poly boat](http://www.headwinds.net/lab/porthole/sea/waveWithBoat.html) and hooked up your nice Animator to it and the water which are now part of a single context.

I was attempting to take a point from the water beneath the boat and apply it's z to the entire boat shape so that the boats rises and falls in sync with the water but didn't quite get it to work so I faked it with a simple crude yo-yo effect. 

I see there is a property called matrix on a shape - does that get or set the matrix? or potentially both...  I imagine you can get the matrix and use its values to do the translation.

**Comment by themadcreator** [comment]
Awesome!

Looks like you've already got it using an SVG. You can even inspect the DOM in Chrome to see the <path>'s being written on each render call.

As for accessing the z coordinate, check out this fiddle: http://jsfiddle.net/ugcw4qdu/63/ 

The trick here is that we want to use the noise function with the same arguments as the point on the water directly below the boat. Since we created a patch for the water with a specific width and height and then translated back by half the width and height, that means that the point under the boat is the mid point of the water patch (if the boat is at the origin). So, we know the x/y to use is half the patch width/patch height.

**Comment by headwinds** [comment]
wow! Well... I'm glad I was at least on the right path but I wouldn't come up with that solution on my own. So I've updated the fiddle and [tried it with the boat](http://jsfiddle.net/headwinds/ycpfvqmq/) which is a free model I found on Turbo Squid. And voila - it floats!

**Comment by themadcreator** [comment]
grats!
