### ISSUE TITLE
Do not block the surface of which is at the rear

### ISSUE THREAD

**Issue by screendle** [themadcreator/seen#17]
Hello! Very good library. Thank you.
I have the following question. Sometimes the model at a certain angle to the fore surface to be rear.
That's what I mean:
![surf_004](https://cloud.githubusercontent.com/assets/18581906/15285112/05e9b144-1b5e-11e6-90b0-5c7ad643ed23.png)
![surf_005](https://cloud.githubusercontent.com/assets/18581906/15285113/05ed836e-1b5e-11e6-88d5-b43d470bbafa.png)
![surf_006](https://cloud.githubusercontent.com/assets/18581906/15285114/05f20966-1b5e-11e6-979a-bbb80ae2a660.png)
How can I fix this moment?

**Comment by themadcreator** [comment]
Hey @screendle,

This happens because we use a "[painter's algorithm](https://en.wikipedia.org/wiki/Painter%27s_algorithm)" for z-ordering. See this line in [scene.coffee](https://github.com/themadcreator/seen/blob/master/src/scene.coffee#L84).

In order to place shapes on top of each other, we sort them by the z-coordinate of the surface centroid in projected screen space. Other methods of determining which shape overlaps which would be extremely expensive to compute and would likely prevent interactive rendering frame rates.

So, it's a necessary trade-off to achieve the high performance of this library at the cost of the occasional rendering artifact like the ones you've posted.

However, if you REALLY do want to alter the order in which the shapes are drawn, you can override the render method of your scene. Take the inherited method's output, and change the order of render models however you like.

In the mean time, I am going to close this issue as "won't fix"
