### ISSUE TITLE
Mouse events of individual elements of the model

### ISSUE THREAD

**Issue by screendle** [themadcreator/seen#19]
Hello! Is it possible to handle the mouse events of individual elements of the model? For example to take and move objects on the same scene?

In other words, if the model is made up of several shapes, can we somehow determine at what shape we clicked?

**Comment by themadcreator** [comment]
Oh man, that would be pretty awesome. There are some technical challenges to this, though:

1. You can determine which element you click if it's rendered in SVG since that is a native DOM mouse event, however, in HTML Canvas, you only get a click on the top-level canvas and would have to compute the element that your mouse was over manually. This could be done, but point-location amongst arbitrary polygons can be expensive and usually requires an additional data structure and algorithm (like a Quad-tree or R-tree).

2. The shapes are redrawn every frame, usually removing the element from the DOM entirely (SVG) or just clearing the whole frame (Canvas). So, the shape that you mousedown might be different than the shape you mouseup on if the shapes and animating underneath your mouse.

3. Currently, there is no way to determine the seen.Shape from the SVG element. This is pretty easy to change, we just need to take the element with a unique id of the shape. This also means the seen.Surface needs a reference to the seen.Shape that contains it.

**Comment by screendle** [comment]
Тhanks, themadcreator! Do you plan to implement such a feature?
While identifying the object, you can use color (if the objects have different colors) using `getImageData` to canvas (path fill for SVG). All this is easy to `seen.Shaders.flat()`. In the case of the shader `diffuse()` to better identify the shapes for the minimum angle between the color vectors in CIE XYZ color space.
