### ISSUE TITLE
How to map a mouse click event to coordinates on Surface?

### ISSUE THREAD

**Issue by michaelwhelehan** [themadcreator/seen#23]
Hi there,

First of all thank you for writing this amazing library! I'm having a great time working with it!

I would like to ask how I would be able to check if a mouse click event is contained by points on a Surface?

I've tried the following but it doesn't seem to be working:

```
    mouseEvent = new seen.MouseEvents('seen-canvas-0')
    mouseEvent.on('mouseUp', (e) ->
     coords = getPageCoords(e)
     quatX = seen.Quaternion.pointAngle(seen.Points.Y(), coords[0] / seen.Quaternion.pixelsPerRadian)
     quatY = seen.Quaternion.pointAngle(seen.Points.X(), coords[1] / seen.Quaternion.pixelsPerRadian)
     point = quatX.multiply(quatY).q
     for surface in shape.surfaces
       bounds = new seen.Bounds(surface.points)
       if bounds.contains point
         surface.fill seen.Colors.rgb(255, 255, 0)
    )
```

Kind Regards
Michael

**Comment by MOctavio** [comment]
Hi @michaelwhelehan 

The issue with canvas is that the elements we add are simple data containing pixels and colors unlike DOM elements wich are more complex objects.
Here is a [Plunker](https://plnkr.co/edit/il41IoREWQ9jDzfxonDi?p=preview) doing some calculations in order to detect a click on a specific are of a canvas, technically it works but I wouldn't suggest you to follow this aproach on prod apps, SVG's are much easier to handle, take a look at this [link](https://developer.mozilla.org/en-US/docs/Web/SVG/Scripting), also there are a lot of good suggestions on stackoverflow.

More info about [Canvas/SVG](http://stackoverflow.com/questions/5882716/html5-canvas-vs-svg-vs-div/5883032#5883032) and about [evenlisteners for SVG](http://stackoverflow.com/questions/12451855/how-to-add-event-listeners-to-objects-in-a-svg).

**Comment by themadcreator** [comment]
Excellent followup, @MOctavio, I'm closing this for now
