### ISSUE TITLE
How can I add text to one surface of a rectangle object?

### ISSUE THREAD

**Issue by m00nlight** [themadcreator/seen#6]
I want to show some text on a surface of a rectangle, how can I do it in seen.js? Or is there any example?

**Comment by themadcreator** [comment]
Hey m00nlight. I've just updated the site with a new version, 0.2.3. It contains greatly improved support for text shapes.

Here is a demo using text: http://seenjs.io/demo-text.html

Unfortunately, we have to do some tricks to make text look like it is projected properly since SVG and Canvas can use only affine transforms on text. See the new seen.Affine class for more details.
